# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190312_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_location',
        ),
    ]
