# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_image_image_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='username',
        ),
    ]
